GetAllHeartbeatsAsync()
Chalden/SFObserver pull request #44
Opened 2020-06-03 11:56 UTC by Chalden

2020-06-03 12:17 UTC, ArmelLagadic requested changes

2020-06-03 12:17 UTC, ArmelLagadic commented on HeartbeatService/HeartbeatService.cs
> +                var enumerable  = this.Heartbeats.CreateEnumerableAsync(tx);
Always await Task.
Dont try to get its Result.

2020-06-03 15:47 UTC, ArmelLagadic approved these changes

2020-06-04 13:26 UTC, Chalden commented
It is working with DataContract. I made set functions private.

GetAllHeartbeatsAsync function works well too.

![getall](https://user-images.githubusercontent.com/37584922/83762341-bbc83280-a677-11ea-9e05-e6fe115159fc.PNG)

2020-06-04 13:58 UTC, ArmelLagadic approved these changes

2020-06-04 14:00 UTC, merged